# Generated by Django 3.1.8 on 2022-05-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190703_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='present',
            name='action_taken',
            field=models.CharField(default='Try again', max_length=200),
            preserve_default=False,
        ),
    ]
