# Generated by Django 3.1.8 on 2022-05-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_present_action_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='present',
            name='action_taken',
        ),
        migrations.AddField(
            model_name='time',
            name='action_taken',
            field=models.CharField(default='Try Again', max_length=200),
            preserve_default=False,
        ),
    ]
