# Generated by Django 3.1.8 on 2022-05-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='person',
            field=models.IntegerField(),
        ),
    ]
